version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    rebase-strategy: "auto"
    schedule:
      interval: daily
    open-pull-requests-limit: 30
    commit-message:
      prefix: "chore"
      include: "scope"
