stages:
- deploy

variables:
  PROJECT: nestcord

.before:
  before_script:

################################################### PROD
deploy:
  stage: deploy
  variables:
    ENV_URL: https://nestcord.globalart.dev
    NAMESPACE: globalart-prod
    HARBOR_PROJECT: gitlab-prod
  environment:
    name: production/prod1
    url: $ENV_URL
    kubernetes:
      namespace: production
  script:
  - source $("/home/gitlab-runner/bin/trdl" use werf "1.2" "stable")
  - source $(werf ci-env gitlab --as-file)
  - werf cr login  -u $HARBOR_USERNAME -p $HARBOR_PASSWORD $HARBOR_HOST 
  - werf converge --namespace=$NAMESPACE
    --env prod
    --kube-config=${KUBECTX_PROD1}
    --skip-tls-verify-registry=true 
    --repo-container-registry=harbor 
    --repo=$HARBOR_HOST/${HARBOR_PROJECT}/$CI_PROJECT_NAME 
    --repo-harbor-username=$HARBOR_USERNAME
    --repo-harbor-password=$HARBOR_PASSWORD 
    --atomic=true 

      
    
