jobs:
  cleanup:
    runs-on: ubuntu-latest
    permissions: write-all

    steps:
    - name: 🗑 Delete deployment
      uses: strumwolf/delete-deployment-environment@v3
      with:
        token: ${{ secrets.GH_TOKEN }}
        environment: github-pages
        onlyRemoveDeployments: true
